config/routes.rb
Rails.application.routes.draw do
  root 'buy_items#index'
  resources :buy_items do
    collection do
      get 'log_view'
      get 'chart_view'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/buy_item.rb
class BuyItem < ApplicationRecord

  #has_many :category

  MIN_PRICE = 2000.freeze
  MAX_PRICE = 100000.freeze
  validates :price, numericality: {only_interger: true, greater_than_or_equal_to:MIN_PRICE, less_than_or_equal_to: MAX_PRICE}

  #一覧表示
  scope :by_month_buy,-> (month) {
    where(created_at: month)
  }

  #購入可能かどうかを判定
  scope :buy_approval, -> (category) {
    where(
      category_id: category,
      created_at: Time.current.all_month
    )  
  }

  #チャート表示用にデータ取得
  scope :chart_scope, -> {
    select("to_char(created_at, 'yyyy-mm') as buy_month, sum(price) as month_price")
    .order("buy_month")
    .group("buy_month")
  }

end

app/models/category.rb
class Category < ApplicationRecord
  #belongs_to :buy_items
  scope :category_list, -> { all.pluck(:name, :id)}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/buy_items_controller.rb
class BuyItemsController < ApplicationController

  def index
    #今月/前月/前々月のデータ取得
    month_hash = {
      this_month: Time.current.all_month, 
      one_month_ago: 1.months.ago.all_month, 
      two_month_ago: 2.months.ago.all_month
    }

    @buy_items_hash = {}
    month_hash.each do |key, value|
      @buy_items_hash[key] = BuyItem.by_month_buy(value)
    end
  end

  def new
    @buy_item = BuyItem.new
  end

  def create
      if BuyItem.buy_approval(params[:buy_item][:category_id]).blank?
          buy_item = params.require(:buy_item).permit(:category_id, :name, :price)
          BuyItem.create(buy_item)
      else
          flash[:error] = "該当カテゴリは、今月既に購入済みです。"
      end
      redirect_to buy_items_path
  end

  #ログ表示画面
  def log_view
    # @buy_items = BuyItem.all
    @q = BuyItem.ransack(params[:q])
    @buy_items = @q.result(distinct: true)
  end

  #チャート表示画面
  def chart_view
    @chart_data = BuyItem.chart_scope.map {|item| [item.buy_month, item.month_price]}
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buy_items_helper.rb
module BuyItemsHelper
end

app/views/buy_items/chart_view.slim
.mb-3
  = column_chart @chart_data, min: 10000, max:50000, width: "15em"

= link_to "一覧へ戻る", buy_items_path, class: 'btn btn-warning btn-lg'

app/views/buy_items/index.slim
- if flash[:error]
  .flash
    = flash[:error]

div.index_btn_area
  = link_to "新規作成", new_buy_item_path, class: 'btn btn-primary btn-lg'
  = link_to "ログ一覧", log_view_buy_items_path, class: 'btn btn-info btn-lg'
  = link_to "チャート一覧", chart_view_buy_items_path, class: 'btn btn-secondary btn-lg'

- @buy_items_hash.each_value do |item|
  div.buy_month_area
  - unless item.first.nil?
    strong
      = item.first.created_at.strftime("%Y/%m")

  div.buy_item_table
    table.table
      thead.thead-default
        tr
          th カテゴリ
          th 項目名
          th 金額
      tbody
        - item.each do |val|
          tr
            td = Category.find(val.category_id).name ||= ""
            td = val.name
            td = val.price

        tr style="font-weight: bold;"
            td colspan=2 style="text-align: rigth;" 合計金額
            td = item.sum(:price)

app/views/buy_items/log_cat.slim
= form_with model: @buy_item, local: true do |item|
  .form-group
    = item.label '承認状態'
    = item.select :select_approval, [["承認のみ",true],["全て",false]], {}, class: 'form-control'

  .form-group
    = item.label 'カテゴリ'
    = item.select :category_id_cont, Category.category_list, {}, class: 'form-control'

= link_to "検索", log_cat_buy_items_path, class: 'btn btn-secondary'

hr

.mb-5
table.table
  thead.thead-default
    tr
      th カテゴリ
      th 項目名
      th 金額
      th 承認
      th 作成日
  tbody
    - @buy_items.each do |item|
      tr
        td = Category.find(item.category_id).name ||= ""
        td = item.name
        td = item.price
        td = (item.approval ? "OK" : "NG")
        td = item.created_at.strftime("%Y/%m")

= link_to "一覧へ戻る", buy_items_path, class: 'btn btn-warning'

app/views/buy_items/log_view.slim
= search_form_for(@q, url: log_view_buy_items_path) do |item|
  = item.label :name_cont, '項目名'
  = item.search_field :name_cont, class: 'form-control'
  = item.submit "検索", class: 'btn btn-light'

hr

- unless @buy_items.nil?
  .mb-5
  table.table
    thead.thead-default
      tr
        th カテゴリ
        th 項目名
        th 金額
        th 作成日
    tbody
      - @buy_items.each do |item|
        tr
          td = Category.find(item.category_id).name ||= ""
          td = item.name
          td = item.price
          td = item.created_at.strftime("%Y/%m")

= link_to "一覧へ戻る", buy_items_path, class: 'btn btn-warning'

app/views/buy_items/new.slim
h1 新規作成

= form_with model: @buy_item, local: true do |item|
  .form-group
    = item.label :category_id, "カテゴリ"
    = item.select :category_id, Category.category_list, {}, class: 'form-control'
  .form-group
    = item.label :name, "項目名"
    = item.text_field :name, class: 'form-control'
  .form-group
    = item.label :price, "金額"
    = item.text_field :price, class: 'form-control'

  div.new_btn_area
    = item.submit '作成', class: 'btn btn-primary btn-lg'
    = link_to "一覧へ戻る", buy_items_path, class: 'btn btn-warning btn-lg'

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | ProtectMoney
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    /= stylesheet_link_tag    "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application'

  body
    .app-title
      .navbar-brand ProtectMoney
    .container
        = yield